import './globals.css'
import type {Metadata} from 'next'
import {ClerkProvider} from '@clerk/nextjs';
import {ChildrenProps} from '@/types/childrenProps';
import {AppLayout} from '@/ui/layout/appLayout';


export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: ChildrenProps) {
    return (
        <ClerkProvider>
            <html lang="en">
            <body className="bg-gray-50 dark:bg-slate-900">
            <AppLayout>
                {children}
            </AppLayout>
            </body>
            </html>
        </ClerkProvider>
    )
}
