import '../globals.css'
import type {Metadata} from 'next'
import {ClerkProvider} from '@clerk/nextjs';
import {ClientAppLayout} from '@/ui/layout/clientAppLayout';
import {notFound} from 'next/navigation';
import {NextIntlClientProvider, useMessages} from 'next-intl';

const locales = ['en', 'pt'];
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children, params: {locale}}: any) {
    const messages = useMessages()
    const isValidLocale = locales.some((cur) => cur === locale);
    if (!isValidLocale) notFound();


    return (
        <ClerkProvider>
            <html lang={locale}>
            <body className="bg-gray-50 dark:bg-slate-900">
            <NextIntlClientProvider messages={messages} locale={locale}>
                <ClientAppLayout >
                    {children}
                </ClientAppLayout>
            </NextIntlClientProvider>
            </body>
            </html>
        </ClerkProvider>
    )
}
